sudo: false

language: php

dist: trusty

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

before_script:
  - composer require satooshi/php-coveralls:2.*
  - composer install
  
script:
  - ./vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml

after_script:
- php vendor/bin/php-coveralls -v

notifications:
  email:
    on_success: never
    on_failure: always