language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm
  - nightly

before_script:
  - composer install
  - composer require atoum/atoum
  
script: vendor/bin/atoum

notifications:
  on_success: never
  on_failure: always