language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

install:
  - composer require php-coveralls/php-coveralls
  - composer install

before_script:
  - mkdir -p build/logs

script:
  - php vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
- travis_retry php vendor/bin/php-coveralls -v

notifications:
  email:
    on_success: never
    on_failure: always