sudo: false

language: php

dist: trusty

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

install:
  - composer require php-coveralls/php-coveralls
  - composer install
  
script:
  - mkdir -p build/logs
  - vendor/bin/phpunit --coverage-clover buld/logs/clover.xml

after_success:
- travis_retry php vendor/bin/php-coveralls

notifications:
  email:
    on_success: never
    on_failure: always